name: snackbar_cs
description: "A customizable Flutter snackbar package with predefined styles for success, error, warning, and info messages."
version: 0.0.2
homepage: https://github.com/Cagdassrgl/snackbar_cs
repository: https://github.com/Cagdassrgl/snackbar_cs
documentation: https://github.com/Cagdassrgl/snackbar_cs#readme

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
